# Generated by Django 6.0.1 on 2026-03-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=234)),
                ('jersey_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('total_matches', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='playerperformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.IntegerField()),
                ('score', models.IntegerField()),
                ('assists', models.CharField(max_length=99)),
                ('fouls', models.IntegerField()),
                ('minutes_played', models.TimeField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coach', models.CharField(max_length=222)),
                ('logo', models.FileField(upload_to='team_image')),
                ('established_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=222)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.sport')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.team'),
        ),
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=221)),
                ('prize', models.IntegerField()),
                ('description', models.CharField(max_length=222)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.sport')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one', models.CharField(max_length=222)),
                ('team_two', models.CharField(max_length=111)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(max_length=88)),
                ('team_one_score', models.IntegerField()),
                ('team_two_score', models.IntegerField()),
                ('is_completed', models.CharField(max_length=222)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=179)),
                ('is_active', models.CharField(max_length=222)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tournament')),
            ],
        ),
    ]
