# Generated by Django 6.0.1 on 2026-04-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.FileField(default=1, upload_to='player_image'),
            preserve_default=False,
        ),
    ]
