# Generated by Django 6.0.1 on 2026-04-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_player_sport_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='total_teams',
            field=models.IntegerField(default=16),
        ),
    ]
