# Generated by Django 6.0.1 on 2026-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_tournament_total_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='entry_fee',
            field=models.IntegerField(default=0),
        ),
    ]
