# Generated by Django 6.0.1 on 2026-04-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_tournamentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='player_name',
            field=models.CharField(default='Unknown', max_length=222),
            preserve_default=False,
        ),
    ]
