# Generated by Django 6.0.1 on 2026-04-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_tournamentregistration_player_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentRegistration',
        ),
    ]
