# Generated by Django 6.0.1 on 2026-05-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_customuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
