# Generated by Django 6.0.1 on 2026-05-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_tournamentregistration_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
